### ISSUE TITLE
The 4k environment does not work in the MH4G[KOP] version.

### ISSUE THREAD

**Issue by Uramiz8429** [Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator#7] opened 2024-11-18 04:55 UTC
Hello, Developer.

I was excited to see the program you developed on Discord, so I installed it. I followed the installation guide and adjusted the high DPI settings, but the overlay does not work.

The CMD console recognized MH4G yesterday, but it does not work in the version of Citra Nightly 2104 that I am using.

Today, when I tried to run it again, the program does not recognize MH4G. The behavior changed from yesterday, which is a bit strange.

I have attached an image of the issue happening today.

I wish you happiness, health, and good luck always.
![Uploading 241118 MH4G error.png…]()

**Comment by Alexander-Lancellott** [comment] 2024-11-18 05:26
Hi, I think the image you attached didn’t upload correctly since it can’t be viewed. Could you confirm the TitleID of the MH4G you’re using? For example, is it `000400000011D700` or `0004000000141A00`? It would also be helpful to know if you’re using any game updates or not.

If we’re in the same Discord group, feel free to look me up and send me a direct message, as I’m likely to respond faster on Discord than on GitHub.

**Comment by Uramiz8429** [comment] 2024-11-18 05:39
<img width="1869" alt="241118 MH4G error" src="https://github.com/user-attachments/assets/c5d603bf-55da-491a-afd0-09a7d81d2f1f">

I see that you intend to upload the image again here.

The game's ID is 00153200 (path: title\00040000\00153200).

There are no additional updates applied to the MH4G game from the base ROM.

For MHXX, I have patched another language version ROM with the language I use.

I tried running a different derivative program (Mandarin) yesterday to see if it was a problem with Citra, but I'm not sure if that affected the recognition issue.

Thank you for your prompt response! ;-)

**Comment by Alexander-Lancellott** [comment] 2024-11-18 06:08
I understand. This is likely expected behavior since I haven’t confirmed support for the Korean version. That’s why I’ve listed the game versions that the overlay should work well with. You can find this compatibility list [here](https://github.com/Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator?tab=readme-ov-file#compatibility), and if you check it, you’ll see that `0004000000153200` is not included.

I’ll see if I can get the Korean version and add support for it, assuming I’m able to replicate the same issue you’re experiencing.

**Comment by Alexander-Lancellott** [comment] 2024-11-18 09:23
MH4G `0004000000153200` should now be supported with [version 1.1.2](https://github.com/Alexander-Lancellott/MH-HP-Overlay-For-3DS-Emulator/releases/tag/v1.1.2), which I released a few minutes ago. On my end, I was only able to replicate the issue where the labels containing the monster information weren’t visible — the same problem you initially experienced. However, I couldn’t replicate the issue where the overlay’s CMD no longer detects the game.

If this issue persists with version 1.1.2, it’s likely that something in your system has been modified, or you’re using a third-party program that interferes with the overlay’s functionality. There could be several causes for this problem, so I suggest the following steps:

1. **Check AHK in the System Tray:**
Ensure that when you launch the overlay, two AHK icons appear in the Windows System Tray. If they do, it means AHK is running correctly, which is crucial as it detects the Citra window and analyzes which game is being executed.

2. **Verify Citra's UDP Port:**
Confirm that Citra's UDP port is open only when a game is running in Citra and not before. If it’s open beforehand, another program might be using it. If it doesn’t appear, it’s possible that the Windows Firewall or another antivirus is blocking it. To check, run the following command in a CMD or PowerShell window: `netstat -ano | findstr 45987` 
This will return a result if the port is in use while Citra is running a game.

3. **Reset Citra Configuration:**
Try resetting Citra to its default settings, as you may have modified something that broke the overlay's expected behavior. To do this, rename the `Citra folder`, usually located at: `C:\Users\YourUserName\AppData\Roaming\Citra` 
Be careful not to delete it, as it contains your save files. Once renamed, relaunch Citra, which should create a new `Citra folder` in Roaming with default settings. Configure only the basics and test the overlay again.

If you’ve followed all these steps and still haven’t resolved the issue, I suggest contacting me via Discord for better assistance. I’ll be closing this issue for now.

**Closed by Alexander-Lancellott** 2024-11-18 09:23 UTC

**Comment by Uramiz8429** [comment] 2024-11-18 10:32
ftp://pc@192.168.0.9:3304/device/Download/Psp/PSP/PPSSPP_STATE/ 에 있는 모든 파일을 D:\Game\EMUL\PSP\memstick\PSP\PPSSPP_STATE 로 복사 하고, 중복 파일 있으면 덮어쓰는 배치 파일을 만들어줘
아래와 같은 배치 파일을 사용하면 됩니다. 이 배치 파일은 지정된 원본 폴더에서 대상 폴더로 모든 파일을 복사하고, 중복 파일이 있으면 덮어쓰게 됩니다.

batch
@echo off
set src="\\192.168.0.9\device\Download\Psp\PSP\PPSSPP_STATE\*"
set dst="D:\Game\EMUL\PSP\memstick\PSP\PPSSPP_STATE"

xcopy %src% %dst% /E /Y

echo 모든 파일이 성공적으로 복사되었습니다.
pause
이 배치 파일을 사용하려면, 위 내용을 텍스트 파일에 저장한 후 확장자를 .bat로 변경하면 됩니다. 그 다음, 배치 파일을 실행하면 됩니다. 문제가 있으면 언제든지 알려주세요!

반대로 하는 것도 만들어줘
아래와 같은 배치 파일을 사용하면, D 드라이브의 파일을 네트워크 위치로 복사하고 중복 파일이 있으면 덮어쓰게 됩니다:

batch
@echo off
set src="D:\Game\EMUL\PSP\memstick\PSP\PPSSPP_STATE\*"
set dst="\\192.168.0.9\device\Download\Psp\PSP\PPSSPP_STATE"

xcopy %src% %dst% /E /Y

echo 모든 파일이 성공적으로 복사되었습니다.
pause
이 배치 파일을 위와 동일한 방법으로 사용하면 됩니다. 위 내용을 텍스트 파일에 저장한 후 확장자를 .bat로 변경한 다음, 파일을 실행하세요. 궁금한 점이 있으면 언제든지 말씀해 주세요!

ftp://pc@192.168.0.9:3304/device/Download/Psp/PSP/PPSSPP_STATE/ 폴더를 여는 배치파일을 만들어줘
FTP 폴더를 여는 배치 파일은 다음과 같이 작성할 수 있습니다. 이 배치 파일은 지정된 FTP 폴더를 Windows 파일 탐색기로 엽니다.

batch
@echo off
start "" "ftp://pc@192.168.0.9:3304/device/Download/Psp/PSP/PPSSPP_STATE/"
pause
이 배치 파일을 사용하려면, 위 내용을 텍스트 파일에 저장한 후 확장자를 .bat로 변경하세요. 그런 다음, 배치 파일을 실행하면 해당 FTP 폴더가 Windows 파일 탐색기로 열릴 것입니다.

추가적인 도움이 필요하면 언제든지 말씀해 주세요!

cmd 상에서 네트워크 드라이버로 이동하는 방법이 있어?
네, Command Prompt(CMD)에서 네트워크 드라이브로 이동할 수 있습니다. 먼저, 네트워크 드라이브를 로컬 드라이브에 매핑해야 합니다. 예를 들어, Z: 드라이브로 네트워크 드라이브를 매핑한 후, 해당 드라이브로 이동하는 방법은 다음과 같습니다.

먼저 네트워크 드라이브를 매핑합니다. CMD 창에 다음 명령어를 입력합니다:

batch
net use Z: \\192.168.0.9\device\Download\Psp\PSP\PPSSPP_STATE /user:pc <비밀번호>
Z:는 매핑할 드라이브 문자입니다.

\\192.168.0.9\device\Download\Psp\PSP\PPSSPP_STATE는 네트워크 드라이브 경로입니다.

<비밀번호>는 네트워크 드라이브에 접근하기 위한 비밀번호입니다.

네트워크 드라이브로 이동합니다:

batch
Z:
위 명령어를 사용하면, 네트워크 드라이브가 로컬 드라이브로 매핑되고, 해당 드라이브로 이동할 수 있습니다.

도움이 되셨길 바랍니다! 더 궁금한 점이 있으면 언제든지 물어봐 주세요. 😊

4k 환경 MH4G[KOP] 버전에서 동작하지 않습니다. 영문으로 번역
The 4k environment does not work in the MH4G[KOP] version.

안녕하세요. 제작자님. 디스코드에서 개발해주신 프로그램을 보고 설레여서 설치를 했습니다. 설치가이드를 보고 고급 dpi 쪽도 설정해 줬으나, 오버레이가 동작하지 않습니다. CMD 실황창에서는 MH4G 를 인식했다고 까지는 나오는데 제가 사용하는 Citra Nighthly 2104 버전에서 동작하지 않습니다. 혹시 특수한 경우에 추가로 설정하는 방법이 있는지 문의 드립니다. 항상 행복하시고, 건강하시며 행운이 깃들길 바랍니다. 영문 번역
Hello, Developer. I was excited to see the program you developed on Discord, so I installed it. I followed the installation guide and adjusted the high DPI settings, but the overlay does not work.

The CMD console recognizes MH4G, but it does not work in the version of Citra Nightly 2104 that I am using.

I would like to inquire if there are any additional settings required for special cases.

I wish you happiness, health, and good luck always.

안녕하세요. 제작자님. 디스코드에서 개발해주신 프로그램을 보고 설레여서 설치를 했습니다. 설치가이드를 보고 고급 dpi 쪽도 설정해 줬으나, 오버레이가 동작하지 않습니다. CMD 실행창에서는 MH4G 를 인식했다고 까지는 나오는데 제가 사용하는 Citra Nighthly 2104 버전에서 동작하지 않습니다. 오늘 다시 실행해보니 프로그램이 MH4G 를 인식하지 못합니다. 어제와 현상이 달라져서 조금 이상합니다. 오늘 현상 이미지 첨부하겠습니다. 항상 행복하시고, 건강하시며 행운이 깃들길 바랍니다. 영문 번역
Hello, Developer.

I was excited to see the program you developed on Discord, so I installed it. I followed the installation guide and adjusted the high DPI settings, but the overlay does not work.

The CMD console recognized MH4G yesterday, but it does not work in the version of Citra Nightly 2104 that I am using.

Today, when I tried to run it again, the program does not recognize MH4G. The behavior changed from yesterday, which is a bit strange.

I have attached an image of the issue happening today.

I wish you happiness, health, and good luck always.

Hi, I think the image you attached didn’t upload correctly since it can’t be viewed. Could you confirm the TitleID of the MH4G you’re using? For example, is it 000400000011D700 or 0004000000141A00? It would also be helpful to know if you’re using any game updates or not. If we’re in the same Discord group, feel free to send me a direct message, as I’m likely to respond faster on Discord than on GitHub. 번역
안녕하세요,

첨부하신 이미지가 제대로 업로드되지 않아 확인할 수 없습니다. 사용 중인 MH4G의 TitleID를 확인해 주시겠어요? 예를 들어, 000400000011D700 또는 0004000000141A00인가요? 또한 게임 업데이트를 사용 중인지도 알려주시면 도움이 될 것 같습니다.

우리가 같은 디스코드 그룹에 있다면, 디스코드에서 직접 메시지를 보내 주셔도 됩니다. GitHub보다 디스코드에서 더 빨리 응답할 수 있습니다.

감사합니다.

아 이미지는 다시 여기 업로드 하겠습니다. 저장 위차상 Game 의 ID 는 00153200 입니다. ( 경로 title\00040000\00153200) MH4G 게임 업데이트는 기본 rom 에서 추가 업데이트 한 내역은 없습니다. MHXX 의 경우에는 다른 언어 버전 ROM에 제가 사용하는 언어 패치를 한적 있습니다. 한글 번역
이미지를 여기 다시 업로드해 주신다고 하셨군요.

게임의 ID는 00153200입니다. (경로 title\00040000\00153200)

MH4G 게임은 기본 ROM에서 추가 업데이트 한 내역은 없습니다.

MHXX의 경우에는 다른 언어 버전 ROM에 사용하시는 언어 패치를 한 적이 있습니다.

다시 한 번 이미지를 첨부해 주시면 문제를 더 잘 이해할 수 있을 것 같습니다. 감사합니다!

이미지를 여기 다시 업로드해 주신다고 하셨군요. 게임의 ID는 00153200입니다. (경로 title\00040000\00153200) MH4G 게임은 기본 ROM에서 추가 업데이트 한 내역은 없습니다. MHXX의 경우에는 다른 언어 버전 ROM에 사용하시는 언어 패치를 한 적이 있습니다. 어제 시트라 문제인가 해서, 다른 파생 프로그램 (만다린)을 실행해본적 있는데 그게 인식 안되는 현상에 영향을 준지는 정확하지 않습니다. 빠른 답변 감사합니다!! 영문 번역
I see that you intend to upload the image again here.

The game's ID is 00153200 (path: title\00040000\00153200).

There are no additional updates applied to the MH4G game from the base ROM.

For MHXX, I have patched another language version ROM with the language I use.

I tried running a different derivative program (Mandarin) yesterday to see if it was a problem with Citra, but I'm not sure if that affected the recognition issue.

Thank you for your prompt response!

MH4G 0004000000153200 should now be supported with version 1.1.2, which I released a few minutes ago. On my end, I was only able to replicate the issue where the labels containing the monster information weren’t visible — the same problem you initially experienced. However, I couldn’t replicate the issue where the overlay’s CMD no longer detects the game. If this issue persists with version 1.1.2, it’s likely that something in your system has been modified, or you’re using a third-party program that interferes with the overlay’s functionality. There could be several causes for this problem, so I suggest the following steps: Check AHK in the System Tray: Ensure that when you launch the overlay, two AHK icons appear in the Windows System Tray. If they do, it means AHK is running correctly, which is crucial as it detects the Citra window and analyzes which game is being executed. Verify Citra's UDP Port: Confirm that Citra's UDP port is open only when a game is running in Citra and not before. If it’s open beforehand, another program might be using it. If it doesn’t appear, it’s possible that the Windows Firewall or another antivirus is blocking it. To check, run the following command in a CMD or PowerShell window: netstat -ano | findstr 45987 This will return a result if the port is in use while Citra is running a game. Reset Citra Configuration: Try resetting Citra to its default settings, as you may have modified something that broke the overlay's expected behavior. To do this, rename the Citra folder, usually located at: C:\Users\YourUserName\AppData\Roaming\Citra Be careful not to delete it, as it contains your save files. Once renamed, relaunch Citra, which should create a new Citra folder in Roaming with default settings. Configure only the basics and test the overlay again. If you’ve followed all these steps and still haven’t resolved the issue, I suggest contacting me via Discord for better assistance. I’ll be closing this issue for now. 번역
MH4G 0004000000153200는 이제 몇 분 전에 출시한 버전 1.1.2에서 지원되어야 합니다. 제 쪽에서는 몬스터 정보를 포함한 레이블이 보이지 않는 문제만 재현할 수 있었고, 이는 귀하가 처음 겪었던 문제와 동일합니다. 그러나 오버레이의 CMD가 더 이상 게임을 감지하지 않는 문제는 재현할 수 없었습니다.

이 문제가 버전 1.1.2에서도 지속된다면, 시스템에 무언가가 수정되었거나 오버레이의 기능을 방해하는 타사 프로그램을 사용하고 있을 가능성이 큽니다. 이 문제의 원인은 여러 가지가 있을 수 있으며, 다음 단계를 시도해 보시기 바랍니다:

시스템 트레이에서 AHK 확인:
오버레이를 실행할 때 Windows 시스템 트레이에 두 개의 AHK 아이콘이 나타나는지 확인하세요. 나타나면 AHK가 제대로 실행되고 있으며, 이는 Citra 창을 감지하고 실행 중인 게임을 분석하는 데 중요합니다.

Citra의 UDP 포트 확인:
Citra의 UDP 포트가 게임이 Citra에서 실행될 때만 열려 있는지 확인하세요. 실행 전에는 열려 있지 않아야 합니다. 만약 다른 프로그램이 사용 중인 경우 또는 Windows 방화벽이나 다른 안티바이러스가 차단하고 있을 수 있습니다. CMD 또는 PowerShell 창에서 다음 명령어를 실행하여 확인할 수 있습니다:

batch
netstat -ano | findstr 45987
이 명령어는 Citra가 게임을 실행하는 동안 포트가 사용 중인지 결과를 반환합니다.

Citra 설정 초기화:
Citra를 기본 설정으로 초기화해 보세요. 수정한 설정이 오버레이의 예상 동작을 깨트렸을 수 있습니다. 이를 위해 보통 위치는 다음과 같습니다: C:\Users\YourUserName\AppData\Roaming\Citra의 Citra 폴더 이름을 변경하십시오. 삭제하지 마시고 저장 파일을 포함하고 있으니 주의하세요. 이름 변경 후 Citra를 다시 시작하면 기본 설정으로 새 Citra 폴더가 Roaming에 생성됩니다. 기본 설정만 구성하고 오버레이를 다시 테스트하십시오.

이 단계를 모두 수행한 후에도 문제가 해결되지 않으면 더 나은 지원을 위해 디스코드를 통해 연락해 주시기 바랍니다. 이 문제는 여기서 닫겠습니다.

안녕하세요! 확인 필요한 부분 확인해도 증상이 동일합니다. 1. 오버레이를 실행할 때 Windows 시스템 트레이에 두 개의 AHK 아이콘이 나타나는지 확인하세요. 나타나면 AHK가 제대로 실행되고 있으며, 이는 Citra 창을 감지하고 실행 중인 게임을 분석하는 데 중요합니다. 시스템 트레이에 2개의 AHK 항목이 실행중입니다. 2.netstat -ano | findstr 45987 이 명령어는 Citra가 게임을 실행하는 동안 포트가 사용 중인지 결과를 반환합니다. 명령어를 입력시 어떠한 피드백도 돌아오지 않았습니다. 3.Citra 설정 초기화: Citra를 기본 설정으로 초기화해 보세요. 수정한 설정이 오버레이의 예상 동작을 깨트렸을 수 있습니다. 이를 위해 보통 위치는 다음과 같습니다: ROAMING 폴더에 기존 폴더를 변경하고 재실행 했으나 동일한 증상입니다. -------------------- 왜인지 알 수 없지만, citra 폴더를 다시 원복 시키고 혹시 해서 기존 압축을 푼 프로그램을 제거하고 다시 오버레이 프로그램을 설치하니 MH4G running 라고 녹색 글씨를 출력했습니다. 오버레이 실행파일에 관리자 권한을 부여한적이 있는데 그거와 관련이 있는지는 모르겠습니다. 도움이 되셨으면 합니다. 항상 즐거운 날 되시길 바랍니다. 영문 번역
Hello!

I have checked all the necessary parts, but the symptoms remain the same.

When the overlay is running, two AHK icons appear in the Windows system tray. This means that AHK is running correctly and detecting the Citra window and analyzing the game being played.

When I enter the command netstat -ano | findstr 45987, there is no feedback returned, even though Citra is running the game.

I reset the Citra configuration to default by renaming the existing folder in the ROAMING directory and relaunching it, but the symptoms remain the same.

For some unknown reason, after restoring the Citra folder, I uninstalled the previously extracted program and reinstalled the overlay program, and now the green text "MH4G running" appears.

I had granted administrative privileges to the overlay executable, but I am not sure if that is related.

I hope this information helps.

Wishing you happy days always.
